### ISSUE TITLE
How to change color of elevated flat button

### ISSUE THREAD

**Issue by Ankit-vtro** [CRED-CLUB/synth-ios#14]
Hello , I am using below code :
        elevatedFlatButton.applyNeuBtnStyle(type: .elevatedFlat, attributedTitle: NSAttributedString(string: "Idle now", attributes: flatTextAttributes))

Now I want to change  elevatedFlatButton color to orange -  which is blue right now , is there a way to do it or can we do it as I didn't understand the explanation on your GitHub page.

**Comment by prashant-shrivastava91** [comment]
you can create an instance of `NeuConstants.NeuButtonCustomModel` and modify `normalBgGradientColors` and `highlightedBgGradientColors` properties of `buttonContentModel`.

**Comment by Ankit-vtro** [comment]
> you can create an instance of `NeuConstants.NeuButtonCustomModel` and modify `normalBgGradientColors` and `highlightedBgGradientColors` properties of `buttonContentModel`.

I tried this was able to change the content colors (normalBgGradientColors & highlightedBgGradientColors) but how can i have the shadow depth of black color like that in  .elevatedFlat of type NeuButtonType ?
