### ISSUE TITLE
Support for Swift Package Manager

### ISSUE THREAD

**Issue by DominatorVbN** [CRED-CLUB/synth-ios#5]
Hey 👋 @prashant-shrivastava91 
Many of us iOS Developer have moved to SPM for dependency management in there project, and it will be awesome if Synth also add support for it too,

I have created an fork and added support for SPM, but not I am not able to open an pull request to repo. 
I am linking the fork URL here.
[My Fork](https://github.com/DominatorVbN/synth-ios)

Thanks for creating this awesome lib ❤️

**Comment by DominatorVbN** [comment]
I am linking the pull request here also.
#6

**Comment by sadiq81** [comment]
+1

**Comment by prashant-shrivastava91** [comment]
closing this as #6 is merged
